version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 8081:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: puttmaster_db
