name: Test & Deploy
on:
  push:

jobs:
  Build_lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run tsc
      - name: Test
        run: npm run test
  Deploy:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
