name: Deploy to review
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_CREATE_TOKEN }}
  FLY_REGION: arn
  FLY_ORG: personal
  INPUT_NAME: fudisc-review-pr

jobs:
  review_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}

    environment:
      name: fu-review
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.3.0
        with:
          name: peerrr-${{ github.event.number }}